### PR TITLE
make gd32vf103.h compatible with C++

### PR DESCRIPTION
**Pull request by XelaRellum**
Use "stdbool.h" instead of yet a nother bool typedef.

### CODE REVIEW

**Comment by JBKingdon** [comment]
Hi, just wondering if there's a reason this hasn't been merged yet?

**Comment by mttbx** [comment]
This is important for porting, please merge. @rgwan

**Comment by richardclli** [comment]
Perhaps nobody is maintaining it.....

**Comment by tuupola** [comment]
I think this is not really maintained. You might be better off using the [Nuclei RISC-V SDK](https://github.com/Nuclei-Software/nuclei-sdk).

**Comment by richardclli** [comment]
Anyway, well I can always fork it and maintain it myself, ha.

**Pull request merged**
